### ISSUE TITLE
大佬能不能讲讲具体的流程啊，有些内容看不懂啊，

### ISSUE THREAD

**Issue by supperlitt** [F8LEFT/SoFixer#1]
大佬能不能讲讲具体的流程啊，有些内容看不懂啊，
例如：
ElfRebuilder.cpp
544行    for (Elf_Dyn* d = si.dynamic; d->d_tag != DT_NULL; ++d) {
si.dynamic是怎么计算出来的，base是怎么计算出来的，可以描述一下么？

**Comment by F8LEFT** [comment]
github不是聊天室，关了。具体流程看文章。
