### ISSUE TITLE
32bit 修复有问题

### ISSUE THREAD

**Issue by HOOKDLL** [F8LEFT/SoFixer#5]
Release v2.1.5 在我mac无法使用
![image](https://user-images.githubusercontent.com/39880388/105478016-99a22400-5cdd-11eb-891f-85460083ce9b.png)
自行编绎后能正常使用,尝试修复32bit so
![image](https://user-images.githubusercontent.com/39880388/105478150-c81fff00-5cdd-11eb-8b63-29a32beebd93.png)
ida打开报错
![image](https://user-images.githubusercontent.com/39880388/105478729-83489800-5cde-11eb-8cfb-3dfb27737bc0.png)
![image](https://user-images.githubusercontent.com/39880388/105478220-e128b000-5cdd-11eb-8954-c7d1598e91a7.png)
导出函数全错误
![image](https://user-images.githubusercontent.com/39880388/105478630-64e29c80-5cde-11eb-9c41-ef2ab0b03716.png)
样本已qq发送给你!请查收,谢谢
旧版无此问题

**Comment by F8LEFT** [comment]
fix in v2.1.6 
[https://github.com/F8LEFT/SoFixer/releases/tag/v2.1.6](url)
顺便在mac上测试了一下，能正常打开，需要设置一下安全性选项。可能弄个签名能方便点吧。
